const SERVER_URL = "https://chloe-server-dice-roller-f9a4h0a7hrdvatg5.centralus-01.azurewebsites.net";


// Wake up the Node.js server when the website loads
async function wakeServer() {
    try {
        const response = await fetch(`${SERVER_URL}/api/wake`);

        if (!response.ok) {
            throw new Error("Unable to wake the server.");
        }

        const data = await response.json();

        console.log("Server status:", data);

    } catch (error) {
        console.error("Server wake-up failed:", error);
    }
}


// Get five random dice numbers from the Node.js server
async function rollFiveDice() {
    try {
        const response = await fetch(`${SERVER_URL}/api/roll-five`);

        if (!response.ok) {
            throw new Error("Unable to roll the dice.");
        }

        const data = await response.json();

        console.log("Dice generated by server:", data.dice);

        return data.dice;

    } catch (error) {
        console.error("Dice roll failed:", error);

        return null;
    }
}


// Main Dice Roller function
async function rollDice() {

    const dice = await rollFiveDice();

    // Stop if the server did not return dice
    if (dice === null) {
        return;
    }

    console.log("Your dice:", dice);


    // Display the results
    document.getElementById("dice1").textContent = dice[0];
    document.getElementById("dice2").textContent = dice[1];
    document.getElementById("dice3").textContent = dice[2];
    document.getElementById("dice4").textContent = dice[3];
    document.getElementById("dice5").textContent = dice[4];
}


// Wake the server when the webpage loads
wakeServer();